factorialNumber
owner6/js-data-analysis pull request #1
Opened 2023-03-10 18:59 UTC by owner6

2023-03-10 20:51 UTC, Dever4eg commented on index.html
> -
Відступи від лівого боку криві. як тільки вкледеність - роби відступ вправо.

2023-03-10 20:52 UTC, Dever4eg commented on index.html
> +      <button type="button" onclick="calculateFactorial()">Обчислити факторіал</button>
краще не використовую onclick. замість цього в джаваскрипті зроби:

```
const factorialButtonElement = document.findById('factorial-button')
factorialButtonElement.addEventListener('click', function () {
    // action here
})
```

2023-03-10 20:53 UTC, Dever4eg commented on index.html
> +      <button type="button" onclick="calculateFactorial()">Обчислити факторіал</button>
це якщо що непрцюючий код. знайди як правильно методи називаються

2023-03-10 20:58 UTC, Dever4eg commented on index.html
> +		<input type="number" id="number" name="number">
якщо в цьому html будуть ще й інші елементи які стосуються інших задач то тоді краще додати префікс factorial

`factorial-number`
`factorial-result`
'factorial-button'

2023-03-10 21:19 UTC, Dever4eg requested changes

2023-03-10 21:19 UTC, Dever4eg commented on index.html
>  </html>
додай порожню строку в кінці файлу

2023-03-11 20:55 UTC, owner6 commented on index.html
> -
вже виправив,

2023-03-11 23:17 UTC, merged