Currencies
owner6/js-data-analysis pull request #3
Opened 2023-03-22 11:59 UTC by owner6

2023-03-22 21:01 UTC, Dever4eg requested changes

2023-03-22 21:01 UTC, dever4eg commented on index.html
> +
Why did you add these empty lines?

2023-03-22 21:01 UTC, dever4eg commented on currencies.html
> +<h1>Конвертер валют</h1>
Отступи знов вліво полізли

2023-03-22 21:01 UTC, dever4eg commented on currencies.html
> +		<option value="karbo">Karbo</option>
А чому тут не всі валюти?

2023-03-22 21:01 UTC, dever4eg commented on currencies.html
> +	<button type="submit">Конвертировать</button>
А чого руснявою?

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +let newCurrensies = currencies.filter (currency => currency.priceInUsd > 10)
Відступи зліва знов неправильні

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +let newCurrensies = currencies.filter (currency => currency.priceInUsd > 10)
помилка в слові Currensies

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +function newCurrensiesObj() {
чому така назва функції? назви виходячи з того що ця функція робить

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +				 return null
Відступи якісь взагалі дикі

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +		if (currency) {
можна використати тернарний оператор, буде красивіше

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +const findObj = (currencyName) => {
чому така назва функції? незрозуміло з назви взагалі що вона робить. який вона об'єкт шукає. і чому об'єкт якщо повертає пона число а не об'єкт

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +	const fromRate = currencies.find(currencies => currencies.name === from_currency).priceInUsd
тут можна використати функцію яку писав раніше

2023-03-22 21:01 UTC, dever4eg commented on currencies.js
> +	//калькуляция коефициента
better to write comments in english

2023-03-22 21:01 UTC, Dever4eg commented on currencies.js
> +form.addEventListener("submit", function(event) {
Ооо, ця цункція нарно вийшла. красиво все.

2023-03-22 21:01 UTC, Dever4eg commented on currencies.js
> +	/*document.write(convertCurrency(1, "bitcoin", "karbo"))*/
такий тимчасовий код краще не комітити

2023-03-22 21:01 UTC, dever4eg commented on styles.css
> +
забагато пустих рядків

2023-03-22 21:03 UTC, Dever4eg commented on styles.css
> +.a1 {
А чому a1? зазвичай не дуже добре називати класи з числами, незрозуміло що то за число таке

2023-03-22 21:04 UTC, Dever4eg commented on currencies.html
> +	<button class="a1" type="submit">Конвертировать</button>
можеш назвати наприклад 'submit-button', або 'primary-button'

2023-03-22 21:04 UTC, Dever4eg commented on currencies.js
> +console.log(getPriceInUsd("karbo"))
В реальному коді краще не комітити console.log. зазвичай їх використовують тільки щоб потестити щось

2023-03-23 17:03 UTC, owner6 commented on currencies.html
> +		<option value="karbo">Karbo</option>
зазвичай роблять пари до 2-3 валют

2023-03-23 17:22 UTC, owner6 commented on currencies.html
> +<h1>Конвертер валют</h1>
код поформатирован

2023-03-23 17:23 UTC, owner6 commented on currencies.html
> +	<button type="submit">Конвертировать</button>
виправлено

2023-03-23 17:32 UTC, owner6 commented on currencies.js
> +let newCurrensies = currencies.filter (currency => currency.priceInUsd > 10)
отформатировал

2023-03-25 21:38 UTC, Dever4eg requested changes

2023-03-25 21:38 UTC, Dever4eg commented on script.js
> +
Тут знов якийсь брудний код. І схоже попав сюди з попереднього пул реквесту. Тут би його в функцію обернути, а не просто вииводити. І той document.write він же повпливає на зовнішній вигляд. краще тоді прибрати його

2023-03-26 12:42 UTC, owner6 commented on index.html
> +
lines deleted

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +	/*document.write(convertCurrency(1, "bitcoin", "karbo"))*/
the сomited code deleted

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +	//калькуляция коефициента
comments  written in English

2023-03-26 22:17 UTC, owner6 commented on styles.css
> +.a1 {
The styles were modified according to the instructions on the video.

2023-03-26 22:17 UTC, owner6 commented on currencies.html
> +	<button class="a1" type="submit">Конвертировать</button>
назву змінено

2023-03-26 22:17 UTC, owner6 commented on styles.css
> +
Removed empty rows in css

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +console.log(getPriceInUsd("karbo"))
Console logs deleted

2023-03-26 22:17 UTC, owner6 commented on script.js
> +
Dirty code deleted

2023-03-26 22:17 UTC, owner6 commented on styles.css
> +.a1 {
стосовно цього коментаря, тут це застаріла версія стилів, а в веткі "Converter currency styles maket" вже стилі переписані

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +let newCurrensies = currencies.filter (currency => currency.priceInUsd > 10)
перейменовано 2 функції щоб більш зрозуміло відображали  головний функціонал функції
![image](https://user-images.githubusercontent.com/72974036/227807203-f988d21d-b5d7-451b-b5d0-7e4d69d57a0e.png)
![image](https://user-images.githubusercontent.com/72974036/227807236-d3a2ece9-c893-414c-824a-715312c68ebe.png)

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +				 return null
indents fixed

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +		if (currency) {
виправлено. тепер функція тернарна
![image](https://user-images.githubusercontent.com/72974036/227807825-d7fda700-68bb-40c4-b044-2f3ac1e7e226.png)

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +const findObj = (currencyName) => {
function name fixed

2023-03-26 22:17 UTC, owner6 commented on currencies.js
> +	const fromRate = currencies.find(currencies => currencies.name === from_currency).priceInUsd
я вже не памятаю як я писав

2023-03-26 22:20 UTC, owner6 commented on currencies.js
> +function newCurrensiesObj() {
назву функції змінено

2023-03-26 22:24 UTC, owner6 commented on currencies.js
> +	const fromRate = currencies.find(currencies => currencies.name === from_currency).priceInUsd
лишаю як є, погоджено з лукашенком олександром грігоричем

2023-03-26 22:49 UTC, owner6 commented on styles.css
> +.a1 {
стилі з ветки були видалені через їх неактуальність, в іншій веткі є нові стилі

2023-03-27 00:01 UTC, Dever4eg approved these changes

2023-03-27 11:41 UTC, merged