Converter currency styles maket
owner6/js-data-analysis pull request #4
Opened 2023-03-25 21:24 UTC by owner6

2023-03-25 21:39 UTC, Dever4eg requested changes

2023-03-25 21:39 UTC, Dever4eg commented on currencies.html
> +	<!----
Закоментований код краще не лишати. Якщо треба подивитись який він був раніше - в тебе є git,  вгьому вся історія є

2023-03-25 21:39 UTC, Dever4eg commented on currencies.html
> +</html>
Бажано додавати порожню строку в кінці файлу

2023-03-25 21:39 UTC, Dever4eg commented on currencies.js
> +		return convertedAmount
Відступ зайвий зліва

2023-03-25 21:39 UTC, Dever4eg commented on currencies.js
> +const imagesTo = {
imagesTo - тут же такі самі зображення, для чого тоді дублювати. можна просто зробити images

2023-03-25 21:39 UTC, Dever4eg commented on index.html
> +
Для чого порожні строки?

2023-03-25 21:39 UTC, Dever4eg commented on styles.css
> +CORE STYLES
Що це?

2023-03-25 21:41 UTC, Dever4eg commented on styles.css
> +CORE STYLES
Дивний коментар, незрозуміло для чого він тут

2023-03-26 21:16 UTC, owner6 commented on styles.css
> +CORE STYLES
ок

2023-03-26 21:20 UTC, owner6 commented on index.html
> +
порожys строки видалені

2023-03-26 21:24 UTC, owner6 commented on currencies.js
> +const imagesTo = {
буде перероблено згідно інструкціх відео

2023-03-26 22:33 UTC, owner6 commented on currencies.html
> +	<!----
закоментований код видалено

2023-03-26 22:36 UTC, owner6 commented on currencies.js
> +		return convertedAmount
відступ зліва видалено, також пробіл між рядками видалено
![image](https://user-images.githubusercontent.com/72974036/227809031-96aa3ebf-51ac-4b78-bd13-9367029e94fa.png)

2023-03-26 22:39 UTC, owner6 commented on currencies.html
> +</html>
![image](https://user-images.githubusercontent.com/72974036/227809184-f32920bf-c999-4e17-b38e-c4106adb9b3a.png)
пусту строку додано

2023-03-27 17:49 UTC, Dever4eg requested changes

2023-03-27 17:49 UTC, Dever4eg commented on currencies.html
> -	<meta name="viewport" content="width=device-width, initial-scale=1.0">
А чому видалив viewport? Його корисно використовувати кращої для адаптивності для маленькиї екранів

2023-03-27 17:49 UTC, Dever4eg commented on currencies.html
> +		<div class="wrapper">
Зайвий відступ зліва для цього всього блогу

2023-03-27 17:49 UTC, dever4eg commented on currencies.html
> +		<script src="currencies.js"></script>
І тут зайвий відступ зліва

2023-03-27 17:49 UTC, dever4eg commented on index.html
> +		<script src="script.js"></script>
І тут відступ для чогось додав зайвий

2023-03-27 17:52 UTC, owner6 commented on currencies.html
> -	<meta name="viewport" content="width=device-width, initial-scale=1.0">
добре поверну, не знав для чого то я побачив content="IE=edge подумав шось повязано з браузером інтернет експлорер чи ейдж браузер

2023-03-27 17:53 UTC, Dever4eg commented
@owner6 Додай скріншот в пул реквест, як виглядає те що ти зробив. В description.

2023-03-27 20:59 UTC, owner6 commented on currencies.html
> +		<div class="wrapper">
побачив, зайвий відступ вже прибрав

2023-03-27 21:00 UTC, owner6 commented on currencies.html
> +		<script src="currencies.js"></script>
прибрав відступ

2023-03-27 21:01 UTC, owner6 commented on index.html
> +		<script src="script.js"></script>
прибрав

2023-03-27 23:13 UTC, dever4eg approved these changes

2023-03-27 23:46 UTC, merged